{% set name = "ipfshttpclient" %}
{% set version = "0.8.0a2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d80e95ee60b02c7d414e79bf81a36fc3c8fbab74265475c52f70b2620812135

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2,<4
    - multiaddr >=0.0.7
    - requests >=2.11
  run:
    - python >=3.6
    - multiaddr >=0.0.7
    - requests >=2.11

test:
  imports:
    - ipfshttpclient
    - ipfshttpclient.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ipfs.io/ipns/12D3KooWEqnTdgqHnkkwarSrJjeMP2ZJiADWLYADaNvUb6SQNyPF/
  summary: Python IPFS HTTP CLIENT library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
