{% set name = "ipfshttpclient" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: feb1033c14c3ac87ee81264176c5beefeaf386385804427160466117ccc43693

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - flit-core >=2,<4
    - multiaddr >=0.0.7
    - requests >=2.11
    - urllib3 >=1.24,<2.0
    - httpx >=0.10.1,<1.0.0
  run:
    - multiaddr >=0.0.7
    - python >=3.5
    - requests >=2.11
    - urllib3 >=1.24,<2.0
    - httpx >=0.10.1,<1.0.0

test:
  imports:
    - ipfshttpclient
    - ipfshttpclient.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ipfs.io/ipns/12D3KooWEqnTdgqHnkkwarSrJjeMP2ZJiADWLYADaNvUb6SQNyPF/
  summary: Python IPFS HTTP CLIENT library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
